# Generated by Django 3.1.6 on 2022-03-02 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='snippet',
            field=models.CharField(default='snippet test', max_length=255),
        ),
    ]
