# Generated by Django 3.1.6 on 2021-02-14 22:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('bio_1', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('birthday', models.CharField(max_length=255)),
                ('website', models.URLField(max_length=255)),
                ('phone', models.IntegerField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('freelance', models.CharField(max_length=255)),
                ('bio_2', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Home_Layout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bio', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('facebook_url', models.URLField(blank=True, max_length=255, null=True)),
                ('instagram_url', models.URLField(blank=True, max_length=255, null=True)),
                ('twitter_url', models.URLField(blank=True, max_length=255, null=True)),
                ('github_url', models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
