# Generated by Django 3.1.6 on 2021-02-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20210214_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intrest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_intrests', models.CharField(max_length=255)),
            ],
        ),
    ]
