# Generated by Django 3.1.6 on 2021-02-15 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_resume'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
