# Generated by Django 3.1.6 on 2021-03-12 20:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_delete_portfolio_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio_Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('client', models.CharField(max_length=255)),
                ('project_date', models.DateField(auto_now_add=True)),
                ('Discription', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
