# Generated by Django 3.1.6 on 2021-03-12 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_portfolio_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio_post',
            name='project_url',
            field=models.URLField(default='non given', max_length=255),
        ),
    ]
