# Generated by Django 3.1.6 on 2021-05-13 00:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_portfolio_post_project_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio_post',
            name='Image',
        ),
        migrations.AddField(
            model_name='portfolio_post',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
