# Generated by Django 3.1.6 on 2022-01-24 21:12

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_auto_20220124_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio_post',
            name='image2',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='portfolio_post',
            name='image3',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='portfolio_post',
            name='category',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
